bases:
- ../default

patchesStrategicMerge:
- manager_image_patch.yaml
- mutatevirtualmachines_opt_mode_patch.yaml
- mutatepods_opt_mode_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
