apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemacpool-mac-controller-manager
  namespace: kubemacpool-system
spec:
  template:
    spec:
      containers:
      - image: quay.io/kubevirt/kubemacpool:latest
        name: manager
